# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://www.wangzhixian.top
date_format: "ordinal"
title: 烛照幽荧
subtitle: "我命由我不由天"
description: "王志贤的个人博客"
keywords: 烛照幽荧, ZhiXian Wang, wzhixian, wangzhixian, 王志贤
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: ZhiXian Wang
organization: 
organization_url: 
github_username: wzhixian
location: Changsha, China
email: 2259654581@qq.com

beiAn: ICP备案证书号：湘ICP备2021020724号-1
beiAnUrl: https://beian.miit.gov.cn/

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: wzhixian/wzhixian.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wzhixian
    repo: blog-comments
    oauth:
        client_id: 5f22246d08323e787fc5
        client_secret: 3d1f20d9ab279af82b29e257d7cbfbff75809dbd
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: wzhixian
    repo: blog-comments
    clientID: 5f22246d08323e787fc5
    clientSecret: 3d1f20d9ab279af82b29e257d7cbfbff75809dbd
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
